
# Config for production environment

# Set the base URL
baseURL: https://crossword.rowanmanning.com/

# Set up site analytics
params:
  analytics:
    fathomSiteId: "NZWPDGTE"
    fathomSiteHostname: "cdn.usefathom.com"
