name: Deploy

on:
  push:
  workflow_run:
    workflows:
      - Fetch leaderboard
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    uses: rowanmanning/actions/.github/workflows/hugo-website.yml@v1
    with:
      hugo-version: '0.101.0'
      timezone: America/New_York
